//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceOrganizationSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConferenceOrganizationSystemEntities : DbContext
    {
        public ConferenceOrganizationSystemEntities()
            : base("name=ConferenceOrganizationSystemEntities")
        {
        }

        private static ConferenceOrganizationSystemEntities _context;

        public static ConferenceOrganizationSystemEntities GetContext()
        {
            if (_context == null)
            {
                _context = new ConferenceOrganizationSystemEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityJurie> ActivityJuries { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Direction> Directions { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventWinner> EventWinners { get; set; }
        public virtual DbSet<HistoryOfUsing> HistoryOfUsings { get; set; }
        public virtual DbSet<Jurie> Juries { get; set; }
        public virtual DbSet<Moderator> Moderators { get; set; }
        public virtual DbSet<Organizator> Organizators { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
