//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceOrganizationSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Activities = new HashSet<Activity>();
            this.ActivityJuries = new HashSet<ActivityJurie>();
            this.EventWinners = new HashSet<EventWinner>();
            this.HistoryOfUsings = new HashSet<HistoryOfUsing>();
        }
    
        public int Id { get; set; }
        public string Nname { get; set; }
        public string Fname { get; set; }
        public string Patronomic { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfBirthday { get; set; }
        public int IdCountry { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
        public int IdRole { get; set; }
        public string PhotoPath
        {
            get
            {
                return "../../Resources/Images/" + Photo;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityJurie> ActivityJuries { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventWinner> EventWinners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryOfUsing> HistoryOfUsings { get; set; }
        public virtual Jurie Jurie { get; set; }
        public virtual Moderator Moderator { get; set; }
        public virtual Organizator Organizator { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual Role Role { get; set; }
    }
}
